[use_case]
input_text = "A system that monitors patient health in real-time, sending alerts to doctors when abnormal values are detected."

# Qwen25_5B, QwenInstruct, Llama3_2_3B_Instruct, Gemma2B
[model_use_case]
ModelUseCase = ["Gemma2B"]

# Qwen25_5B, QwenInstruct, Llama3_2_3B_Instruct, Gemma2B
[UML]
ModelUML = ["Gemma2B"]